services:
  redis:
    image: redis:7-alpine
    container_name: company-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  redisdata:
