# Generated by Django 5.1.7 on 2025-08-11 15:31

import django.db.models.deletion
import interviews.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.CharField(default=interviews.models.generate_candidat_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('metierRecherche', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('branche', models.CharField(max_length=100)),
                ('universite', models.CharField(max_length=150)),
                ('diplome', models.CharField(max_length=150)),
                ('anneeDiplome', models.PositiveIntegerField()),
                ('competences', models.JSONField()),
                ('experience', models.CharField(max_length=255)),
                ('matchingScore', models.PositiveIntegerField()),
                ('dateCandidature', models.DateTimeField()),
                ('status', models.CharField(choices=[('Preselectionne', 'Préselectionné'), ('Refuse', 'Refusé'), ('Invite', 'Invité'), ('EntretienPasse', 'Entretien Passé')], default='Preselectionne', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metier', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('branche', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('typecontrat', models.CharField(max_length=50)),
                ('salaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='interviews.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='interviews.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('duree_limite', models.PositiveIntegerField(help_text='Durée en secondes')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.offre')),
            ],
        ),
    ]
