# Generated by Django 5.1.7 on 2025-08-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_candidats', to='interviews.candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre_candidats', to='interviews.offre')),
            ],
        ),
    ]
