# Generated by Django 5.1.7 on 2025-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_offrecandidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='niveau',
            field=models.CharField(choices=[('Facile', 'Facile'), ('Moyen', 'Moyen'), ('Difficile', 'Difficile')], default='Facile', max_length=20),
        ),
    ]
