# Generated by Django 5.1.7 on 2025-08-16 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_question_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='dateCandidature',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
