# Generated by Django 5.1.7 on 2025-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_candidat_datecandidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('Preselectionne', 'Préselectionné'), ('Refuse', 'Refusé'), ('Invite', 'Invité'), ('EntretienPasse', 'Entretien Passé'), ('Retire', 'Retiré'), ('Pending', 'En attente'), ('Entretient', 'Entretien'), ('EnProcessus', "En Processus d'entretien"), ('EnNegotiation', 'En négociation'), ('Recrute', 'Recruté')], default='Preselectionne', max_length=30),
        ),
    ]
