# Generated by Django 5.1.7 on 2025-08-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_entretien_termine_alter_candidat_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Entretien', 'verbose_name_plural': 'Entretiens'},
        ),
    ]
