# Generated by Django 5.1.7 on 2025-08-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_alter_entretien_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSelectionnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('temps_attribue', models.IntegerField(help_text='Temps en secondes accordé à cette question')),
                ('entretien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_selectionnees', to='interviews.entretien')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='interviews.question')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('entretien', 'question')},
            },
        ),
    ]
