# Generated by Django 5.1.7 on 2025-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_questionselectionnee'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EXPIRE', 'Expiré')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='entretien',
            name='video_reponses',
            field=models.FileField(blank=True, null=True, upload_to='entretiens/'),
        ),
    ]
