# Generated by Django 5.1.7 on 2025-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_entretien_statut_entretien_video_reponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entretien',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20),
        ),
    ]
