# Generated by Django 5.1.7 on 2025-08-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_alter_entretien_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='offre',
            name='recruteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='interviews.recruteur'),
        ),
    ]
