# Generated by Django 4.2.23 on 2025-08-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_alter_entretien_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntretienAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('queued', 'queued'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='queued', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entretien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='interviews.entretien')),
            ],
        ),
    ]
