# Generated by Django 5.1.7 on 2025-08-25 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_recruteur_offre_recruteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
