# Generated by Django 5.1.7 on 2025-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_offre_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='status',
        ),
        migrations.AddField(
            model_name='offrecandidat',
            name='status',
            field=models.CharField(choices=[('Preselectionne', 'Préselectionné'), ('Refuse', 'Refusé'), ('Invite', 'Invité'), ('EntretienPasse', 'Entretien Passé'), ('Retire', 'Retiré'), ('Pending', 'En attente'), ('Entretient', 'Entretien'), ('EnProcessus', "En Processus d'entretien"), ('EnNegotiation', 'En négociation'), ('Recrute', 'Recruté')], default='Preselectionne', max_length=30),
        ),
    ]
