# Generated by Django 5.1.7 on 2025-08-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0014_alter_offrecandidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrecandidat',
            name='status',
            field=models.CharField(choices=[('Preselectionne', 'Préselectionné'), ('Refuse', 'Refusé'), ('Invite', 'Invité'), ('EntretienPasse', 'Entretien Passé'), ('Retire', 'Retiré'), ('Pending', 'En attente'), ('Entretient', 'Entretien'), ('EnProcessus', "En Processus d'entretient"), ('EnNegotiation', 'En négociation'), ('Recrute', 'Recruté')], default='Preselectionne', max_length=30),
        ),
    ]
