# Generated by Django 5.1.7 on 2025-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0015_alter_offrecandidat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
