# Generated by Django 5.1.7 on 2025-08-29 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0016_entretien_feedback_entretien_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='nombre_questions_entretien',
            field=models.PositiveIntegerField(default=4, help_text='Nombre de questions par entretien pour cette offre', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
