# Generated by Django 5.1.7 on 2025-08-29 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0017_entretien_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='nombre_questions_entretien',
            field=models.PositiveIntegerField(default=5, help_text='Nombre de questions par entretien pour cette offre', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
