# Generated by Django 4.2.23 on 2025-08-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_entretienanalyse'),
        ('interviews', '0018_alter_offre_nombre_questions_entretien'),
    ]

    operations = [
    ]
