# Generated by Django 4.2.23 on 2025-09-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_question_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='active',
        ),
    ]
