# Generated by Django 4.2.23 on 2025-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0021_remove_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretien',
            name='date_invitation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='date_vue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
