# Generated by Django 4.2.23 on 2025-09-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0022_entretien_date_invitation_entretien_date_vue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='date_invitation',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_vue',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='vu',
        ),
    ]
